version: "3.4"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./insta-frontend/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

  backend:
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
